[build]
builder = "NIXPACKS"

[build.env]
NIXPACKS_STACK = "ubuntu-22"
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_PATH = "."     # backend está na raiz

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 65"
healthcheckPath = "/"
